import Head from "next/head";
import React from "react";
import Header from "../comps/Header";
import Description from "../comps/Description";
import Images from "../comps/Images";
import Script from "next/script";

const Home = () => {
  return (
    <>
      <Head>
        <title>Frontend Mentor | eCommerce Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        {/* <script src="/script.js" defer></script> */}
      </Head>
      <Script src="/script.js" defer />
      <Header />
      <main>
        <Images />
        <Description />
      </main>
    </>
  );
};

export default Home;
